server:
  port: 10000

#因为当前的eureka是单机的，所以需要做一些配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否注册到其他的eureka上
    fetch-registry: false #是否合并其他eureka上的数据(获取eureka注册信息)
    serviceUrl:
      # defaultZone: http://localhost:10000/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #curl风格为  http://user:123@localhost:10000/eureka
  server:
    enable-self-preservation: false

security:
  basic:
    enabled: true   #开启安全配置，也就是需要密码，如果不需要设置为false。这个参数必须放在application.yml中，不允许放在bootstrap.yml中
  user:
    name: user1
    password: 1234  #设置了用户名密码后，我们可以修改地址的访问风格为 curl 风格


